# Generated by Django 4.2.7 on 2023-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
